spring:
  application:
    name: aws-learning
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
      instance-profile: true
      use-default-aws-credentials-chain: true
    region:
      static: eu-west-3
    stack:
      auto: false
